export const ADD_PLATE   = 'ADD_CARTE';
export const DELETE_PLATE = 'DELETE_CARTE';
export const GET_ALL_Plat = 'GET_ALL_Plat';
export const GET_ALL_CARD = 'GET_ALL_CARD';
export const DELETECARTE = 'DELETECARTE';
export const GET_DATA_response_CART= 'GET_DATA_response';
export const  UPDATE_PLATE = 'UPDATE_PLATE';
export const GET_ALL_ORDER ="GET_ALL_ORDER ";
export const GETALLUSERFORMAPI ="getusersFromApi";